core_core:
    resource: "@CoreCoreBundle/Resources/config/routing.yml"
    prefix:   /

core_menu:
    resource: "@CoreMenuBundle/Resources/config/routing.yml"
    prefix:   /

core_user:
    resource: "@CoreUserBundle/Resources/config/routing.yml"
    prefix:   /

MH3U_menu:
    resource: "@MH3UMenuBundle/Resources/config/routing.yml"
    prefix:   /

MH3U_combination:
    resource: "@MH3UCombinationBundle/Resources/config/routing.yml"
    prefix:   /

MH3U_armor:
    resource: "@MH3UArmorBundle/Resources/config/routing.yml"
    prefix:   /

MH3U_weapon:
    resource: "@MH3UWeaponBundle/Resources/config/routing.yml"
    prefix:   /

MH3U_item:
    resource: "@MH3UItemBundle/Resources/config/routing.yml"
    prefix:   /



