services:
    core_user.locale_listener:
        class: Core\UserBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    core_user.login_listener:
            class: Core\UserBundle\EventListener\LoginListener
            arguments: [@security.context, @router]
            tags:
                - { name: kernel.event_listener, event: security.authentication.success, method: handle }
                - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    core_user.profile.form.type:
        class: Core\UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: core_user_profile }