<?php

namespace MH3U\QuestBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestRankRepository extends EntityRepository
{
}
