<?php

namespace MH3U\LocationBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRankRepository extends EntityRepository
{
}
