services:
    core.menu_builder:
        class: Core\MenuBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    core.menu.navbar:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: core.menu_builder
        factory_method: navBarMenu
        arguments: ["@request", "@security.context"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: core_navbar } # The alias is what is used to retrieve the menu