<?php

namespace MH3U\ItemBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemMonsterTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemMonsterTypeRepository extends EntityRepository
{
}
