<?php

namespace MH3U\ItemBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemMonsterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemMonsterRepository extends EntityRepository
{
}
