<?php

namespace MH3U\ItemBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemGroupRepository extends EntityRepository
{
}
