<?php

namespace MH3U\CombinationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CombinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CombinationRepository extends EntityRepository
{
}
